# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ea3d653053ed6c119a712ffaac8ffc6afef829ded47cbd16b52e76301603f63cda098904331ab1b62a9ac14933d15db3de0949b20167fe00efa03673c0bac5

test:
  secret_key_base: 2118bd9d09ccfb6e93edd0bb3ce33257d578fcbd47e47b57660e08c9bb55f3135152ba5f23fa94dafa4f4fccfe396543f057f94dacf1fdec308ccd714c20d7f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
